/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-16 02:42:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class copyright_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Ienovo/Desktop/server/webapps/ROOT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1546872448000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Title</title>\r\n");
      out.write("    <script>\r\n");
      out.write("        function extend(num){\r\n");
      out.write("\r\n");
      out.write("            if(num==1)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('first');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==2)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('second');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==3)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('third');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==4)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('fourth');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==5)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('fifth');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==6){\r\n");
      out.write("                var obj = document.getElementById('sixth');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==7){\r\n");
      out.write("                var obj = document.getElementById('seven');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                var obj = document.getElementById('eighth');\r\n");
      out.write("                obj.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function out(num){\r\n");
      out.write("            if(num==1)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('first');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==2)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('second');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==3)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('third');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==4)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('fourth');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==5)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('fifth');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==6)\r\n");
      out.write("            {\r\n");
      out.write("                var obj = document.getElementById('sixth');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(num==7){\r\n");
      out.write("                var obj = document.getElementById('seven');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                var obj = document.getElementById('eighth');\r\n");
      out.write("                obj.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"mainWrap\">\r\n");
      out.write("    <div class=\"link\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>友情链接</li>\r\n");
      out.write("            <li><a href=\"http://www.dgut.edu.cn\">东莞理工学院</a></li>\r\n");
      out.write("            <li><a href=\"http://jwc.dgut.edu.cn\">东莞理工学院教务处</a></li>\r\n");
      out.write("            <li><a href=\"http://sw.dgut.edu.cn\">东莞理工学院计算机与网络安全学院</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"final\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"left\">© 2018,UML Group 2</li>\r\n");
      out.write("            <li class=\"right\">联系我们</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
